package kpm

import (
	"encoding/json"
	"fmt"
	"io"
	"strings"
)

// FormatDotenv writes entries as KEY=value lines with a warning header.
func FormatDotenv(w io.Writer, entries []ResolvedEntry) error {
	fmt.Fprintln(w, "# WARNING: contains plaintext secrets — do not commit")
	fmt.Fprintln(w, "# Generated by kpm export")
	fmt.Fprintln(w)
	for _, e := range entries {
		if _, err := fmt.Fprintf(w, "%s=%s\n", e.EnvKey, e.PlainValue); err != nil {
			return err
		}
	}
	return nil
}

// FormatShell writes entries as export KEY='value' lines.
// Single quotes prevent shell expansion; embedded single quotes are escaped.
func FormatShell(w io.Writer, entries []ResolvedEntry) error {
	for _, e := range entries {
		escaped := strings.ReplaceAll(string(e.PlainValue), "'", "'\\''")
		if _, err := fmt.Fprintf(w, "export %s='%s'\n", e.EnvKey, escaped); err != nil {
			return err
		}
	}
	return nil
}

// FormatJSON writes entries as a JSON object {"KEY": "value", ...}.
func FormatJSON(w io.Writer, entries []ResolvedEntry) error {
	m := make(map[string]string, len(entries))
	for _, e := range entries {
		m[e.EnvKey] = string(e.PlainValue)
	}
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	return enc.Encode(m)
}
