package kpm

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
)

// ShellInit outputs shell code that loads KPM into the current shell.
// Detects shell from $SHELL or accepts explicit shell name.
// Output is designed to be eval'd: eval "$(kpm shell-init)"
func ShellInit(w io.Writer, shell string) error {
	if shell == "" {
		shell = filepath.Base(os.Getenv("SHELL"))
	}

	configDir := ConfigDir()
	shellEnvTmpl := filepath.Join(TemplatesDir(), "shell-env.template")

	// Check if KPM is configured — if not, warn on stderr and write nothing to stdout.
	configPath := filepath.Join(configDir, "config.yaml")
	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		fmt.Fprintln(os.Stderr, "kpm: not configured. Run: kpm quickstart")
		return nil
	}

	switch shell {
	case "bash", "zsh", "sh":
		writePosixHook(w, shellEnvTmpl)
	case "fish":
		writeFishHook(w, shellEnvTmpl)
	default:
		writePosixHook(w, shellEnvTmpl)
	}

	return nil
}

func writePosixHook(w io.Writer, shellEnvPath string) {
	fmt.Fprintf(w, `# KPM shell integration (generated by kpm shell-init)
if [ -f "%s" ]; then
    eval "$(kpm env --from '%s' --output shell 2>/dev/null)"
fi
export KPM_LOADED=1
`, shellEnvPath, shellEnvPath)
}

func writeFishHook(w io.Writer, shellEnvPath string) {
	fmt.Fprintf(w, `# KPM shell integration (generated by kpm shell-init)
if test -f "%s"
    kpm env --from '%s' --output shell 2>/dev/null | source
end
set -gx KPM_LOADED 1
`, shellEnvPath, shellEnvPath)
}
